apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        skills: app
      tolerations:
      - key: skills
        operator: Equal
        value: app
        effect: NoSchedule
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}/skills-{{ .Values.appName }}-repo:{{ .Values.tag }}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
