apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
